routes/admin.php
<?php

routes/web.php
<?php

use App\Http\Controllers\Admin\Airpots\AirportController;
use App\Http\Controllers\Admin\CountryStateCity\CountryStateCityController;
use App\Http\Controllers\Admin\Customers\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\Facilities\FacilityController;
use App\Http\Controllers\Admin\Faqs\FaqController;
use App\Http\Controllers\Admin\Hotels\HotelController;
use App\Http\Controllers\Admin\Images\ImageController;
use App\Http\Controllers\Admin\Orders\OrderController;
use App\Http\Controllers\Admin\Reviews\ReviewController;
use App\Http\Controllers\Admin\Vehicles\VehicleController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\Rooms\RoomController;
use App\Http\Controllers\Frontend\HomeController as HomeControllerFrontend;
use App\Http\Controllers\Frontend\HotelController as HotelControllerFrontend;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login', [LoginController::class, 'adminLogin'])->name('admin.login');
Route::post('/admin/login', [LoginController::class, 'adminAuthenticate'])->name('admin.authenticate');
//admin menu
Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('hotels/get-ajax-hotels', [HotelController::class, 'getHotels'])->name('get.hotels.ajax');
    Route::post('hotels/update-status-hotel/{id}', [HotelController::class, 'updateStatusHotel'])->name('update.status.hotel');

    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::post('rooms/set-rooms', [RoomController::class, 'setRooms'])->name('rooms.set.ajax');
    Route::delete('rooms/delete-rooms/{id}', [RoomController::class, 'deleteRooms'])->name('rooms.delete.ajax');
    Route::put('rooms/update-rooms/{id}', [RoomController::class, 'updateRooms'])->name('rooms.update.ajax');
    Route::get('rooms/get-rooms/{id}', [RoomController::class, 'getRooms'])->name('rooms.get.ajax');
    Route::get('images/get-images', [ImageController::class, 'getImages'])->name('images.get.ajax');
    Route::post('images/set-images', [ImageController::class, 'setImages'])->name('images.post.ajax');
    Route::post('images/set-title-images', [ImageController::class, 'setTitleImages'])->name('images.title.post.ajax');
    Route::resource('images', ImageController::class);
    Route::resource('facilities', FacilityController::class);
    Route::get('facilities/get-facility/{id}', [FacilityController::class, 'getFacility'])->name('facility.get.ajax');
    Route::post('facilities/set-facility', [FacilityController::class, 'setFacility'])->name('facility.set.ajax');
    Route::put('facilities/update-facility/{id}', [FacilityController::class, 'updateFacilities'])->name('facility.update.ajax');
    Route::delete('facilities/delete-facility/{id}', [FacilityController::class, 'deleteFacility'])->name('facility.delete.ajax');

    Route::post('review/update-status-review/{id}', [ReviewController::class, 'updateStatusReview'])->name('update.review.status');
    Route::resource('reviews', ReviewController::class);
    Route::resource('faqs', FaqController::class);
    Route::resource('airports', AirportController::class);
    Route::resource('vehicles', VehicleController::class);

    Route::resource('orders', OrderController::class);
    Route::resource('customers', CustomerController::class);

    Route::get('/country-state-city', [CountryStateCityController::class, 'index'])->name('country.index');
    Route::post('/country-state-city/get-state', [CountryStateCityController::class, 'getState'])->name('post.state.index');
    Route::post('/country-state-city/get-city', [CountryStateCityController::class, 'getCity'])->name('post.city.index');
});

Route::get('/crawler',[HotelControllerFrontend::class,'crawler'])->name('crawl.data');
Route::post('/add-review/{id}',[HotelControllerFrontend::class,'addReview'])->name('add.review');
Route::get('/get-session-room',[HotelControllerFrontend::class,'getSessionRoom'])->name('session.get.room');

//web module
Route::get('/', function () {
    return redirect(app()->getLocale());
});
$frontRoutes = function () {
    Route::group([
        'prefix' => '{locale}',
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['setLocale','subDomain']], function () {
        Route::get('/hotel/{slug}', [HotelControllerFrontend::class, 'show']);
        Route::get('/', [HotelControllerFrontend::class, 'index']);
    });
};
Route::domain('{subdomain}.'.config('app.domain_name'))->group($frontRoutes);
Route::domain(config('domain_name'))->group($frontRoutes);

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'title', 'path'
    ];


    /**
     * @return BelongsToMany
     */
    public function hotels(): BelongsToMany
    {
        return $this->belongsToMany(Hotel::class);
    }

    /**
     * @return BelongsToMany
     */
    public function rooms(): BelongsToMany
    {
        return $this->belongsToMany(Room::class);
    }


}

app/Http/Controllers/Admin/Images/ImageController.php
<?php

namespace App\Http\Controllers\Admin\Images;

use App\Exceptions\ExceptionInterface;
use App\Http\Controllers\Admin\BaseControllerInterface;
use App\Http\Controllers\Controller;
use App\Http\Requests\ImageStoreRequest;
use App\Services\Admin\Images\ImageServiceInterface;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ImageController extends Controller
{
    /**
     * @var ImageServiceInterface
     */
    private $service;

    /**
     * ImageController constructor.
     * @param ImageServiceInterface $service
     */
    public function __construct(ImageServiceInterface $service)
    {
        $this->service = $service;
    }

    public function index()
    {
        $dataset = $this->service->index();

        return view('admin.image.index', compact(['dataset']));
    }

    public function create()
    {
        $dataset = $this->service->create();

        return view('admin.image.create', compact(['dataset']));
    }

    /**
     * @param ImageStoreRequest $request
     * @return RedirectResponse
     */
    public function store(ImageStoreRequest $request)
    {
        try {
            $this->service->store($request);

            return redirect()
                ->back()
                ->with('success', 'form has been submitted successfully');

        } catch (ExceptionInterface $exception) {
            return back()->withErrors($exception->getMessage());
        }
    }

    public function destroy(int $id,Request $request)
    {
        try {
           return $this->service->destroy($id,$request);

            return redirect()
                ->back()
                ->with('success', 'image has deleted');

        }catch (ExceptionInterface $exception)
        {
            return back()->withErrors($exception->getMessage());
        }
    }


    public function show(int $id)
    {
        // TODO: Implement show() method.
    }

    public function edit(int $id)
    {
        // TODO: Implement edit() method.
    }

    public function update(int $id, Request $request)
    {
        // TODO: Implement update() method.
    }

    /**
     * @param Request $request
     */
    public function getImages(Request $request)
    {
        try {
            if($request->ajax()){
                $dataset = $this->service->getImages($request);

                return view('admin.image.get_ajax', compact(['dataset']));
            }

        }catch (ExceptionInterface $exception)
        {
            return Response()->json(['status'=>false,'error'=>$exception->getMessage()]);
        }
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function setImages(Request $request)
    {
        try {
            if($request->ajax()){

                $dataset = $this->service->setImages($request);
                return Response()->json($dataset);
            }

        }catch (ExceptionInterface $exception)
        {
            return Response()->json(['status'=>false,'error'=>$exception->getMessage()]);
        }
    }


    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function setTitleImages(Request $request)
    {
        try {
            if($request->ajax()){

                $dataset = $this->service->setTitleImages($request);
                return Response()->json($dataset);
            }

        }catch (ExceptionInterface $exception)
        {
            return Response()->json(['status'=>false,'error'=>$exception->getMessage()]);
        }
    }

}

resources/views/admin/image/create.blade.php
@extends('admin.layouts.master')

@section('HeadScripts')
    <link href="{{url('/')}}/assets/plugins/file-upload/file-upload-with-preview.min.css" rel="stylesheet" type="text/css">

@endsection
@section('Navbar')
@endsection
@section('Content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>
                                    {{__('Image Insert')}}
                                </h4>
                            </div>
                        </div>
                    </div>
                    <hr/>
                {!! Form::open(['url'=>route('images.store'),'enctype'=>"multipart/form-data",'method' => 'post']) !!}
@csrf
                    <div class="custom-file-container" data-upload-id="mySecondImage">
                        <div class="form-group">
                            <label for="title">{{__('Title')}} </label>
                            <input required id="image_title" type="text" name="image_title" placeholder=""
                                   class="form-control" value="{{ Request()->old('title')}}">
                        </div>

                        <div class="form-group">
                            <label for="image">{{__('Image')}} </label>
                            <input required type="file" name="files[]" multiple class="form-control" accept="image/*">

                        </div>




                    </div>

                    <!-- End Tab Content -->
                    <div class="col-12 col-md-12 col-lg-12 text-right">
                        <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
                    </div>
                    {!!Form::close()!!}
                </div>
            </div>

        </div>

    </div>

@endsection
@section('FootScripts')
    <script src="{{url('/')}}/assets/plugins/file-upload/file-upload-with-preview.min.js"></script>

    <script>
        var secondUpload = new FileUploadWithPreview('mySecondImage')
    </script>
@endsection

resources/views/admin/image/get_ajax.blade.php
<div class="files-wraps  view-grid">
    @if(isset($dataset['images']) && $dataset['images']->count()>0)

        @foreach($dataset['images'] as $image)
            <div class="file-item image/svg is-image" id="imageBox_{{$image->id}}">
                <div title="logo-white" class="inner">
                    <button type="button" id="{{$image->id}}" onclick="deleteImage(this)"
                            rel="{{url('storage/'.sprintf('%s%s',$image->path,$image->name))}}"
                            class="btn btn-success btn-block mb-4 mr-2 selectedImage">Kaldır
                    </button>

                    <div class="file-thumb"><img
                            src="{{url('storage/'.sprintf('%s%s',$image->path,$image->name))}}">
                        <input name="image_title" style="width:119px" value="{{$image->title}}" id="{{$image->id}}"
                               onkeyup="updateTitle(this)">

                        <label>Kapak</label><input name="hotel_image_flag[{{$image->id}}]" value="{{$image->pivot->flag}}"
                                                   @if($image->pivot->flag == 1 ){{'checked'}}@endif type="checkbox"  >

                    </div>

                </div>
            </div>
        @endforeach
            <div id="hiddenImageUploadBox">
                @foreach($dataset['images'] as $image)
                     <input type="hidden" name="selectedImages[]" value="{{$image->id}}">
                @endforeach
        </div>
    @else
        <div id="hiddenImageUploadBox"></div>
    @endif
</div>

@section('ajaxFootScript')
    @parent
    <script>
        let image_url = '{{route('images.get.ajax')}}';
        let image_set_url = '{{route('images.post.ajax')}}';

        $('#files').change(function (e) {
            e.preventDefault();

            let files = e.target.files;

            if (files[0].name.length > 0) {

                let fd = new FormData();
                $.each(files, function (key, image) {
                    console.log(image);
                    fd.append('files[]', image, image.name);
                });


                $.ajax({
                    url: image_set_url,
                    type: "POST",
                    data: fd,
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function (data) {

                        $.each(data, function (key, val) {
                            url = '{{url('storage')}}/' + val.path + val.name;

                            $('.view-grid').prepend('<div class="file-item image/svg is-image" id="imageBox_' + val.id + '">\n' +
                                '<div title="logo-white" class="inner">' +
                                ' <button type="button" id="' + val.id + '" onclick="deleteImage(this)"' +
                                ' rel="' + url + '"' +
                                ' class="btn btn-success btn-block mb-4 mr-2 selectedImage">Kaldır' +
                                '  </button>' +
                                ' <div class="file-thumb"><img src="' + url + '" >' +
                                ' </div>' +
                                '  <input name="image_title" style="width:119px" value="' + val.title + '" id="' + val.id + '" onkeyup="updateTitle(this)">' +
                                '  <label>Kapak</label><input name="hotel_image_flag['+val.id+']" value="1" type="checkbox"  id="' + val.id + '">' +
                                '</div>' +
                                '</div>');
                            $('#hiddenImageUploadBox').append('<input type="hidden" name="selectedImages[]" value="' + val.id + '">')

                        });
                    },
                    error: function (data) {
                        let errors = data.responseJSON;
                        console.log(errors);
                    }
                });
            }
        });

        $(document).on('click', '.pagination a', function (event) {
            event.preventDefault();
            getImagesData(this);
        });

        $(document).on('click', '.ajax_search', function (event) {
            event.preventDefault();
            getImagesData(this);
        });


        function getImagesData(e) {

            let page_id = $(e).attr('href') != 'undefined' ?? $(e).attr('href').split('page=')[1];
            let title = $('#ax_search_text').val() ?? '';
            let formData = {
                '_token': token,
                'page': page_id,
                'title': title
            }

            $.ajax({
                url: image_url,
                type: "GET",
                data: formData,
                success: function (data) {
                    $('#fileList').html(data);
                },
                error: function (data) {
                    let errors = data.responseJSON;
                    console.log(errors);
                }
            });
        }

        function insertImages(data) {
            let image_id = $(data).attr('id');
            let image_data = $(data).attr('rel');
            let image_box = $('#imageBox_' + image_id).val();
            $('.attach-demo').append('<div class="image-item" id="image-item-' + image_id + '">\n' +
                '<div class="inner"><span class="delete btn btn-sm btn-danger">' +
                '<i class="fa fa-trash" onclick="deleteImage(' + image_id + ')"></i></span>\n' +
                '<img src="' + image_data + '"></div>\n' +
                '</div>');

            $('.files-wraps').append('<input type="hidden" name="selectedImages[]" value="' + image_id + '">')

            $('#imageBox_' + image_id).fadeOut();
        }

        function deleteImage(data) {
            let imageId = $(data).attr('id');
            $('#imageBox_' + imageId).remove();
            // $('#image-item-' + imageId).fadeOut();
            $('input[name="selectedImages[]"]').map(function () {
                if (this.value == imageId) {
                    $(this).remove();
                }
                ;
            }).get();
        }


        function updateTitle(e) {
            let updateTitleUrl = "{{route('images.title.post.ajax')}}";
            let id = $(e).attr('id');
            let title = $(e).val() ?? '';
            let formData = {
                '_token': token,
                'id': id,
                'title': title
            }

            $.ajax({
                url: updateTitleUrl,
                type: "POST",
                data: formData,
                success: function (data) {
                    console.log(data);
                },
                error: function (data) {
                    let errors = data.responseJSON;
                    console.log(errors);
                }
            });
        }


    </script>
@endsection

resources/views/admin/image/index.blade.php
@extends('admin.layouts.master')

@section('HeadScripts')
    <link rel="stylesheet" type="text/css" href="{{url('/')}}assets/admin/plugins/table/datatable/datatables.css">
    <link rel="stylesheet" type="text/css" href="{{url('/')}}assets/admin/plugins/table/datatable/dt-global_style.css">
    <link rel="stylesheet" type="text/css" href="{{url('/')}}assets/admin/plugins/select2/select2.min.css">
@endsection
@section('Navbar')
@endsection
@section('Content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">

                <button class="btn btn-primary collapsed mb-2" data-toggle="collapse" data-target="#filter"
                        aria-expanded="true" aria-controls="filter">
                    <i class="fa fa-filter mr-1"></i>Filtrele
                </button>
                <a class="btn btn-primary mb-2" href="{{route('images.create')}}">
                    <i class="fa fa-plus mr-1"></i>{{__('Ekle')}} </a>
                <div id="toggleAccordion">
                    @include('admin.partials.filter.image')
                    </div>


                <div class="widget-content widget-content-area br-6">
                    <div class="table-responsive mb-4 mt-4">
                        <table id="product" class="table table-hover" style="width:100%">
                            <thead>
                            <tr>
                                <th>{{__('Title')}}</th>
                                <th>{{__('Process')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($dataset['images'] as $data)
                                <tr>
                                    <td>{{$data->title}}</td>
                                    <td>

                                        <a title="{{__('Delete')}}" class="delete" onclick="return confirm('{{__('Are you sure you want to delete')}}')" href="#" id="{{$data->id}}"><i
                                                class="fas fa-trash"></i></a>
                                    </td>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $dataset['images']->links() }}
                    </div>
                </div>
            </div>

        </div>

    </div



@endsection