routes/admin.php
<?php

routes/web.php
<?php

use App\Http\Controllers\Admin\Airpots\AirportController;
use App\Http\Controllers\Admin\CountryStateCity\CountryStateCityController;
use App\Http\Controllers\Admin\Customers\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\Facilities\FacilityController;
use App\Http\Controllers\Admin\Faqs\FaqController;
use App\Http\Controllers\Admin\Hotels\HotelController;
use App\Http\Controllers\Admin\Images\ImageController;
use App\Http\Controllers\Admin\Orders\OrderController;
use App\Http\Controllers\Admin\Reviews\ReviewController;
use App\Http\Controllers\Admin\Vehicles\VehicleController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\Rooms\RoomController;
use App\Http\Controllers\Frontend\HomeController as HomeControllerFrontend;
use App\Http\Controllers\Frontend\HotelController as HotelControllerFrontend;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login', [LoginController::class, 'adminLogin'])->name('admin.login');
Route::post('/admin/login', [LoginController::class, 'adminAuthenticate'])->name('admin.authenticate');
//admin menu
Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('hotels/get-ajax-hotels', [HotelController::class, 'getHotels'])->name('get.hotels.ajax');
    Route::post('hotels/update-status-hotel/{id}', [HotelController::class, 'updateStatusHotel'])->name('update.status.hotel');

    Route::resource('hotels', HotelController::class);
    Route::resource('rooms', RoomController::class);
    Route::post('rooms/set-rooms', [RoomController::class, 'setRooms'])->name('rooms.set.ajax');
    Route::delete('rooms/delete-rooms/{id}', [RoomController::class, 'deleteRooms'])->name('rooms.delete.ajax');
    Route::put('rooms/update-rooms/{id}', [RoomController::class, 'updateRooms'])->name('rooms.update.ajax');
    Route::get('rooms/get-rooms/{id}', [RoomController::class, 'getRooms'])->name('rooms.get.ajax');
    Route::get('images/get-images', [ImageController::class, 'getImages'])->name('images.get.ajax');
    Route::post('images/set-images', [ImageController::class, 'setImages'])->name('images.post.ajax');
    Route::post('images/set-title-images', [ImageController::class, 'setTitleImages'])->name('images.title.post.ajax');
    Route::resource('images', ImageController::class);
    Route::resource('facilities', FacilityController::class);
    Route::get('facilities/get-facility/{id}', [FacilityController::class, 'getFacility'])->name('facility.get.ajax');
    Route::post('facilities/set-facility', [FacilityController::class, 'setFacility'])->name('facility.set.ajax');
    Route::put('facilities/update-facility/{id}', [FacilityController::class, 'updateFacilities'])->name('facility.update.ajax');
    Route::delete('facilities/delete-facility/{id}', [FacilityController::class, 'deleteFacility'])->name('facility.delete.ajax');

    Route::post('review/update-status-review/{id}', [ReviewController::class, 'updateStatusReview'])->name('update.review.status');
    Route::resource('reviews', ReviewController::class);
    Route::resource('faqs', FaqController::class);
    Route::resource('airports', AirportController::class);
    Route::resource('vehicles', VehicleController::class);

    Route::resource('orders', OrderController::class);
    Route::resource('customers', CustomerController::class);

    Route::get('/country-state-city', [CountryStateCityController::class, 'index'])->name('country.index');
    Route::post('/country-state-city/get-state', [CountryStateCityController::class, 'getState'])->name('post.state.index');
    Route::post('/country-state-city/get-city', [CountryStateCityController::class, 'getCity'])->name('post.city.index');
});

Route::get('/crawler',[HotelControllerFrontend::class,'crawler'])->name('crawl.data');
Route::post('/add-review/{id}',[HotelControllerFrontend::class,'addReview'])->name('add.review');
Route::get('/get-session-room',[HotelControllerFrontend::class,'getSessionRoom'])->name('session.get.room');

//web module
Route::get('/', function () {
    return redirect(app()->getLocale());
});
$frontRoutes = function () {
    Route::group([
        'prefix' => '{locale}',
        'where' => ['locale' => '[a-zA-Z]{2}'],
        'middleware' => ['setLocale','subDomain']], function () {
        Route::get('/hotel/{slug}', [HotelControllerFrontend::class, 'show']);
        Route::get('/', [HotelControllerFrontend::class, 'index']);
    });
};
Route::domain('{subdomain}.'.config('app.domain_name'))->group($frontRoutes);
Route::domain(config('domain_name'))->group($frontRoutes);

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Spatie\Translatable\HasTranslations;

class Room extends GeneralModel
{
    use HasFactory;
    use HasTranslations;

    public $timestamps = false;

    protected $fillable = [
        'title',
        'detail',
        'status'
    ];

    public $translatable = [
        'title','detail'
    ];

    /**
     * @return BelongsToMany
     */
    public function images(): BelongsToMany
    {
        return $this->belongsToMany(Image::class)->withPivot('flag');;
    }

    public function hotels()
    {
        return $this->belongsToMany(Hotel::class)->withPivot('quantity');;
    }
}

app/Http/Controllers/Admin/Rooms/RoomController.php
<?php

namespace App\Http\Controllers\Admin\Rooms;

use App\Exceptions\ExceptionInterface;
use App\Http\Controllers\Admin\BaseControllerInterface;
use App\Http\Controllers\Controller;
use App\Http\Requests\RoomStoreRequest;
use App\Http\Requests\SetRoomsRequest;
use App\Services\Admin\Rooms\RoomServiceInterface;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class RoomController extends Controller
{

    /**
     * @var RoomServiceInterface
     */
    private $service;

    public function __construct(RoomServiceInterface $service)
    {
        $this->service = $service;
    }


    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $dataset = $this->service->index();

        return view('admin.room.index', compact(['dataset']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        $dataset = $this->service->create();

        return view('admin.room.create', compact(['dataset']));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RoomStoreRequest $request
     * @return RedirectResponse
     */
    public function store(RoomStoreRequest $request)
    {
        try {
            $this->service->store($request);

            return redirect()
                ->back()
                ->with('success', 'form has been submitted successfully');

        } catch (ExceptionInterface $exception) {
            return back()->withErrors($exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View|RedirectResponse
     */
    public function show(int $id)
    {
        try {

            $dataset = $this->service->show($id);

            return view('admin.room.show', compact(['dataset']));

        } catch (ExceptionInterface $exception) {
            return back()->withErrors($exception->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RoomStoreRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(RoomStoreRequest  $request, int $id)
    {
        try {
            $this->service->update($id,$request);

            return redirect()
                ->back()
                ->with('success', 'form has been updated successfully');

        } catch (ExceptionInterface $exception) {
            return back()->withErrors($exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }

    public function setRooms(SetRoomsRequest $request)
    {
        try {
            $data = $this->service->setRooms($request);
            return response()->json($data);

        } catch (ExceptionInterface $exception) {
            return response()->json(['success' => false,'error'=>$exception->getMessage()]);
        }
    }

    public function updateRooms(int $id, Request $request)
    {
        try {


            $data = $this->service->updateRooms($id, $request);
            return response()->json($data);

        } catch (ExceptionInterface $exception) {
            return response()->json(['success' => false,'error'=>$exception->getMessage()]);
        }
    }

    /**
     * @param int $id
     * @return JsonResponse
     */
    public function getRooms(int $id)
    {
        try {
            $data = $this->service->getRooms($id);
            return response()->json($data);

        } catch (ExceptionInterface $exception) {
            return response()->json(['success' => false,'error'=>$exception->getMessage()]);
        }
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function deleteRooms(Request $request)
    {
        try {
            $data = $this->service->deleteRooms($request);
            return response()->json($data);

        } catch (ExceptionInterface $exception) {
            return response()->json(['success' => false,'error'=>$exception->getMessage()]);
        }
    }
}

resources/views/admin/room/create.blade.php
@extends('admin.layouts.master')

@section('HeadScripts')
@endsection
@section('Navbar')
@endsection
@section('Content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>
                                    {{__('Room Insert')}}
                                </h4>
                            </div>
                        </div>
                    </div>
                    <hr/>
                {!! Form::open(['url'=>route('rooms.store'),'enctype'=>"multipart/form-data",'method' => 'post']) !!}

                    <!-- Tab Content -->
                    <ul class="nav nav-tabs  mb-3 mt-3" id="simpletab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="main-tab" data-toggle="tab"
                               href="#main"
                               role="tabpanel" aria-controls="main"
                               aria-selected="true">Hotel Seç</a>
                        </li>
                        @foreach(config('app.available_locales') as $i=>$locale)
                            <li class="nav-item">
                                <a class="nav-link" id="{{$locale}}-tab" data-toggle="tab"
                                   href="#{{$locale}}"
                                   role="tabpanel" aria-controls="{{$locale}}"
                                   aria-selected="false">{{strtoupper($locale)}}</a>
                            </li>
                        @endforeach
                        <li class="nav-item">
                            <a class="nav-link  " id="main-tab" data-toggle="tab"
                               href="#images"
                               role="tabpanel" aria-controls="images"
                               aria-selected="false">{{__('Images')}}</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="simpletabContent">
                        <div class="tab-pane fade show active" id="main" role="tabpanel" aria-labelledby="images-tab">
                            <div class="form-group">
                                <label for="title">{{__('Hotel ismi')}} </label>
                                <input  id="hotel_name" type="text" name="hotel_name" placeholder="{{__('Hotel İsmi Giriniz')}}"
                                        class="typeahead form-control" value="{{ Request()->old('hotel_name')}}" autocomplete="off">

                                 <input type="hidden" name="hotel_id" id="hotel_id" value="">
                            </div>
                            <div class="form-group">
                                <label for="quantity">{{__('Oda adeti')}} </label>
                                <input  id="quantity" type="text" name="quantity" placeholder="{{__('Ada Adeti')}}"
                                        class="form-control" value="{{ Request()->old('quantity')}}">
                            </div>
                        </div>

                    @foreach(config('app.available_locales') as $i=>$locale)
                            <div class="tab-pane fade " id="{{$locale}}" role="tabpanel"
                                 aria-labelledby="{{$locale}}-tab">

                                <div class="widget-content widget-content-area">
                                    <div class="form-group">
                                        <label for="title_{{ $locale }}">{{__('Title')}} </label>
                                        <input id="title_{{ $locale }}" type="text" name="title.{{$locale}}" placeholder=""
                                               class="form-control" value="{{ Request()->old('title_'.$locale)}}">
                                    </div>

                                    <div class="form-group">
                                        <label for="detail_{{ $locale }}">{{__('Detail')}} </label>
                                        <input id="detail_{{ $locale }}" type="text" name="detail.{{$locale}}" placeholder=""
                                               class="form-control" value="{{ Request()->old('detail_'.$locale)}}">
                                    </div>
                                </div>
                            </div>
                        @endforeach

                        <div class="tab-pane fade " id="images" role="tabpanel" aria-labelledby="images-tab">
                            <div class="form-group">
                                <label for="title">{{__('Title')}} </label>
                                <input  id="image_title" type="text" name="image_title" placeholder=""
                                       class="form-control" value="{{ Request()->old('title')}}">
                            </div>

                            <div class="form-group">
                                <label for="image">{{__('Image')}} </label>
                                <input required type="file" name="files[]" multiple class="form-control" accept="image/*">

                            </div>
                        </div>
                    </div>
                    <!-- End Tab Content -->
                    <div class="col-12 col-md-12 col-lg-12 text-right">
                        <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
                    </div>
                    {!!Form::close()!!}
                </div>
            </div>

        </div>

    </div>

@endsection
@section('FootScripts')
    <script src="{{url('/')}}/assets/js/bootstrap3-typeahead.min.js"></script>

    <script>


        let hotelName = $('#hotel_name').val();
        let formData = {
            '_token': '{{ csrf_token() }}',
            'name': encodeURI(hotelName),

        };

        let path = '{{route('get.hotels.ajax')}}';
        let productIds = new Object();

        $('input.typeahead').typeahead({
            autoSelect: true,
            minLength: 2,
            delay: 400,
            source:  function (query, process) {
                return $.get(path, { query: query }, function (data) {
                    $.getJSON( path,formData, function ( jsonData )
                    {
                        let productNames = new Array();

                        $.each( jsonData, function ( index, product )
                        {
                            productNames.push( product.name );
                            productIds[product.name] = product.id;
                        } );
                        return process(productNames);
                    });
                });
            },
            updater: function (item) {
                console.log(productIds[item],item); //access it here
                $('#hotel_id').val(productIds[item]);
              return item
            }

        });

</script>
@endsection

resources/views/admin/room/index.blade.php
@extends('admin.layouts.master')

@section('HeadScripts')
    <link rel="stylesheet" type="text/css" href="{{url('/')}}assets/admin/plugins/table/datatable/datatables.css">
    <link rel="stylesheet" type="text/css" href="{{url('/')}}assets/admin/plugins/table/datatable/dt-global_style.css">
    <link rel="stylesheet" type="text/css" href="{{url('/')}}assets/admin/plugins/select2/select2.min.css">
@endsection
@section('Navbar')
@endsection
@section('Content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">

                <button class="btn btn-primary collapsed mb-2" data-toggle="collapse" data-target="#filter"
                        aria-expanded="true" aria-controls="filter">
                    <i class="fa fa-filter mr-1"></i>Filtrele
                </button>
                <a class="btn btn-primary mb-2" href="{{route('rooms.create')}}">
                    <i class="fa fa-plus mr-1"></i>{{__('Ekle')}} </a>
                <div id="toggleAccordion">
                    <div id="filter" class="collapse mt-2" aria-labelledby="headingOne1" data-parent="#toggleAccordion">
                        <div class="widget-content widget-content-area br-6 mb-2">
                            {!! Form::open(['method'=>'get']) !!}
                            <div class="row">
                                <div class="col-xl-6 col-md-6 col-sm-6 col-6">
                                    <div class="form-group mb-4">
                                        <label for="formGroupExampleInput2">Durum</label>
                                        {!! Form::select('status',[''=>'Hepsini Listele','1'=>'Aktif','0'=>'Pasif'], \Illuminate\Support\Facades\Request::get('status'), ['class'=>' form-control basic']) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-12 col-lg-12 text-right">
                                <button type="submit" class="btn btn-primary">Filtrele</button>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>


                <div class="widget-content widget-content-area br-6">
                    <div class="table-responsive mb-4 mt-4">
                        <table id="product" class="table table-hover" style="width:100%">
                            <thead>
                            <tr>
                                <th>{{__('Hotel Adı')}}</th>
                                <th>{{__('Title')}}</th>
                                <th>{{__('İşlemler')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($dataset['rooms'] as $data)
                                <tr>
                                    <td>{{$data->hotels()->first()->name}}</td>
                                    <td>{{$data->getTranslation('title',app()->getLocale())}}</td>

                                    <td>
                                        <a title="{{__('Edit')}}" href="{{route('rooms.show',['room'=>$data->id])}}"><i
                                                class="fas fa-edit"></i></a>
                                        <a title="{{__('Delete')}}" class="delete" onclick="return confirm('{{__('Are you sure you want to delete')}}')" href="#" id="{{$data->id}}"><i
                                                class="fas fa-trash"></i></a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $dataset['rooms']->links() }}
                    </div>
                </div>
            </div>

        </div>

    </div



@endsection

resources/views/admin/room/show.blade.php
@extends('admin.layouts.master')

@section('HeadScripts')
@endsection
@section('Navbar')
@endsection
@section('Content')
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>
                                    {{__('Room Insert')}}
                                </h4>
                            </div>
                        </div>
                    </div>
                    <hr/>
                {!! Form::open(['url'=>route('rooms.update',['room'=>$dataset['room']->id]),'enctype'=>"multipart/form-data",'method' => 'put']) !!}

                <!-- Tab Content -->
                    <ul class="nav nav-tabs  mb-3 mt-3" id="simpletab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="main-tab" data-toggle="tab"
                               href="#main"
                               role="tabpanel" aria-controls="main"
                               aria-selected="true">Hotel Seç</a>
                        </li>
                        @foreach(config('app.available_locales') as $i=>$locale)
                            <li class="nav-item">
                                <a class="nav-link" id="{{$locale}}-tab" data-toggle="tab"
                                   href="#{{$locale}}"
                                   role="tabpanel" aria-controls="{{$locale}}"
                                   aria-selected="false">{{strtoupper($locale)}}</a>
                            </li>
                        @endforeach
                        <li class="nav-item">
                            <a class="nav-link  " id="main-tab" data-toggle="tab"
                               href="#images"
                               role="tabpanel" aria-controls="images"
                               aria-selected="false">{{__('Images')}}</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="simpletabContent">
                        <div class="tab-pane fade show active" id="main" role="tabpanel" aria-labelledby="images-tab">
                            <div class="form-group">
                                <label for="title">{{__('Hotel ismi')}} </label>
                                <input  id="hotel_name" type="text" name="hotel_name" placeholder="{{__('Hotel İsmi Giriniz')}}"
                                        class="typeahead form-control" value="{{ $dataset['room']->hotels()->first()->name}}" autocomplete="off">

                                <input type="hidden" name="hotel_id" id="hotel_id" value="{{ $dataset['room']->hotels()->first()->id}}">
                            </div>
                            <div class="form-group">
                                <label for="quantity">{{__('Oda adeti')}} </label>
                                <input  id="quantity" type="text" name="quantity" placeholder="{{__('Ada Adeti')}}"
                                        class="form-control" value="{{$dataset['room']->hotels()->first()->pivot->quantity}}">
                            </div>
                        </div>

                        @foreach(config('app.available_locales') as $i=>$locale)
                            <div class="tab-pane fade " id="{{$locale}}" role="tabpanel"
                                 aria-labelledby="{{$locale}}-tab">

                                <div class="widget-content widget-content-area">
                                    <div class="form-group">
                                        <label for="title_{{ $locale }}">{{__('Title')}} </label>
                                        <input id="title_{{ $locale }}" type="text" name="title.{{$locale}}" placeholder=""
                                               class="form-control" value="{{$dataset['room']->getTranslation('title',$locale,false)}}">
                                    </div>

                                    <div class="form-group">
                                        <label for="detail_{{ $locale }}">{{__('Detail')}} </label>
                                        <input id="detail_{{ $locale }}" type="text" name="detail.{{$locale}}" placeholder=""
                                               class="form-control" value="{{ $dataset['room']->getTranslation('detail',$locale,false)}}">
                                    </div>
                                </div>
                            </div>
                        @endforeach

                        <div class="tab-pane fade " id="images" role="tabpanel" aria-labelledby="images-tab">
                            <div class="form-group">
                                <label for="title">{{__('Title')}} </label>
                                <input  id="image_title" type="text" name="image_title" placeholder=""
                                        class="form-control" value="@if($dataset['room']->images()->first()){{$dataset['room']->images()->first()->title}}@endif">
                            </div>

                            <div class="form-group">
                                <label for="image">{{__('Image')}} </label>
                                <input type="file" name="files[]" multiple class="form-control" accept="image/*">

                            </div>

                            @foreach($dataset['room']->images()->get() as $i=>$image)
                                <div class="media" id="image_{{$i}}" style="text-align: left">
                                    <div class="n-chk">
                                        <label class="new-control new-radio radio-classic-dark" style="height: 18px;">
                                            <a href="#"
                                               onclick="deleteImage('{{$i}}','{{$image->id}}','{{ $image->path }}','{{ $image->name }}')">
                                                <span class="new-control-indicator">x</span> </a>
                                        </label>
                                    </div>

                                    <div class="media-body">
                                        <img class="rounded" height="100px" style="padding: 10px"
                                             src="{{url('storage/'.sprintf('%s%s',$image->path,$image->name))}}"
                                             alt="pic1">

                                    </div>
                                </div>

                                <!-- media list end-->
                            @endforeach
                        </div>
                    </div>
                    <!-- End Tab Content -->
                    <div class="col-12 col-md-12 col-lg-12 text-right">
                        <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
                    </div>
                    {!!Form::close()!!}
                </div>
            </div>

        </div>

    </div>

@endsection
@section('FootScripts')
    <script src="{{url('/')}}/assets/js/bootstrap3-typeahead.min.js"></script>

    <script>


        let hotelName = $('#hotel_name').val();
        let formData = {
            '_token': '{{ csrf_token() }}',
            'name': encodeURI(hotelName),

        };

        let path = '{{route('get.hotels.ajax')}}';
        let productIds = new Object();

        $('input.typeahead').typeahead({
            autoSelect: true,
            minLength: 2,
            delay: 400,
            source:  function (query, process) {
                return $.get(path, { query: query }, function (data) {
                    $.getJSON( path,formData, function ( jsonData )
                    {
                        let productNames = new Array();

                        $.each( jsonData, function ( index, product )
                        {
                            productNames.push( product.name );
                            productIds[product.name] = product.id;
                        } );
                        return process(productNames);
                    });
                });
            },
            updater: function (item) {
                console.log(productIds[item],item); //access it here
                $('#hotel_id').val(productIds[item]);
                return item
            }

        });

        function deleteImage(layerId, id, path, name) {
            confirm("Are You sure want to delete image?");

            let url = '{{ route("images.destroy", ":id") }}';
            url = url.replace(':id', id);

            $.ajax({
                url: url,
                type: "DELETE",
                data: {
                    '_token': '{{ csrf_token() }}',
                    'path': path,
                    'name': name,
                    'id': id,
                },
                success: function (data) {
                    $("#image_" + layerId).html(data);
                },
                error: function () {

                }
            });
        }

    </script>
@endsection